// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ClientsDocumentDataSlicesSlice = TopDividerSlice;

/**
 * Content for Clients documents
 */
interface ClientsDocumentData {
  /**
   * title field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Title ( Must )
   * - **API ID Path**: clients.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Description ( Must )
   * - **API ID Path**: clients.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Clients*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClientsDocumentDataSlicesSlice> /**
   * Meta Title field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: clients.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Clients*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: clients.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Clients*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Clients document from Prismic
 *
 * - **API ID**: `clients`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ClientsDocumentData>,
    "clients",
    Lang
  >;

type ClientsPostDocumentDataSlicesSlice = never;

/**
 * Content for Client Post documents
 */
interface ClientsPostDocumentData {
  /**
   * title field in *Client Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Title ( Must )
   * - **API ID Path**: clients_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Client Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Description ( Must )
   * - **API ID Path**: clients_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Client Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * year field in *Client Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Enter Signed Year ( Must )
   * - **API ID Path**: clients_post.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  year: prismic.DateField;

  /**
   * type field in *Client Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Enter Type ( Must )
   * - **Default Value**: actor
   * - **API ID Path**: clients_post.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"actor" | "serie" | "production", "filled">;

  /**
   * Slice Zone field in *Client Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ClientsPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Client Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: clients_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Client Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: clients_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Client Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clients_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Client Post document from Prismic
 *
 * - **API ID**: `clients_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientsPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ClientsPostDocumentData>,
    "clients_post",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | WorkWithUsSlice
  | IntegrationSlice
  | LandingSlice
  | CarouselSlice
  | MiniServicesSlice
  | LogosMarqueeSlice
  | BriefSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NewsPageDocumentDataSlicesSlice = HeroSectionSlice | NewsSliderSlice;

/**
 * Content for News Page documents
 */
interface NewsPageDocumentData {
  /**
   * Slice Zone field in *News Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsPageDocumentDataSlicesSlice> /**
   * Meta Title field in *News Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *News Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * News Page document from Prismic
 *
 * - **API ID**: `news_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NewsPageDocumentData>,
    "news_page",
    Lang
  >;

/**
 * Item in *News Post → Tags*
 */
export interface NewsPostDocumentDataTagsItem {
  /**
   * Tag field in *News Post → Tags*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select a tag for the news post
   * - **API ID Path**: news_post.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tag: prismic.SelectField<
    "Most Popular" | "Hot right now" | "Most recent" | "Most read"
  >;
}

type NewsPostDocumentDataSlicesSlice = NewsSliderSlice;

/**
 * Content for News Post documents
 */
interface NewsPostDocumentData {
  /**
   * Title field in *News Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: News post title
   * - **API ID Path**: news_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * mainImage field in *News Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.mainimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainimage: prismic.ImageField<never>;

  /**
   * Tags field in *News Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tags: prismic.GroupField<Simplify<NewsPostDocumentDataTagsItem>>;

  /**
   * Date field in *News Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Publication date
   * - **API ID Path**: news_post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Description field in *News Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description or excerpt of the news post
   * - **API ID Path**: news_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Content field in *News Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Main content of the news post
   * - **API ID Path**: news_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *News Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsPostDocumentDataSlicesSlice> /**
   * Meta Title field in *News Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta title for SEO
   * - **API ID Path**: news_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta description for SEO
   * - **API ID Path**: news_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * image field in *News Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * News Post document from Prismic
 *
 * - **API ID**: `news_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NewsPostDocumentData>,
    "news_post",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactSlice
  | ServicesSlice
  | TeamSlice
  | DisplaySlice
  | VideoSlice
  | AnimatedGridSlice
  | HeroSectionSlice
  | CarouselSlice
  | WorkWithUsSlice
  | LandingSlice
  | AboutLowerSlice
  | BriefSlice
  | IntegrationSlice
  | TopDividerSlice
  | NewsSliderSlice
  | MiniServicesSlice
  | LogosMarqueeSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation Links*
 */
export interface SettingsDocumentDataNavItemsItem {
  /**
   * Link Label field in *Settings → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter link text
   * - **API ID Path**: settings.nav_items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a link
   * - **API ID Path**: settings.nav_items[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;
}

/**
 * Item in *Settings → Social Links*
 */
export interface SettingsDocumentDataSocialItemsItem {
  /**
   * Social Platform field in *Settings → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select platform
   * - **API ID Path**: settings.social_items[].platform
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  platform: prismic.SelectField<
    "Instagram" | "Facebook" | "Twitter" | "LinkedIn" | "YouTube" | "TikTok"
  >;

  /**
   * Social Link field in *Settings → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter social media URL
   * - **API ID Path**: settings.social_items[].social_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_url: prismic.LinkField;

  /**
   * Icon Name field in *Settings → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select icon
   * - **API ID Path**: settings.social_items[].icon_name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_name: prismic.SelectField<
    "Instagram" | "Facebook" | "Twitter" | "LinkedIn" | "YouTube" | "TikTok"
  >;
}

/**
 * Item in *Settings → Footer Secondary Links*
 */
export interface SettingsDocumentDataFooterSecondaryLinksItem {
  /**
   * Link Label field in *Settings → Footer Secondary Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter link text
   * - **API ID Path**: settings.footer_secondary_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Footer Secondary Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a link
   * - **API ID Path**: settings.footer_secondary_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter site title (e.g. Tag Media)
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Navigation Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_items: prismic.GroupField<Simplify<SettingsDocumentDataNavItemsItem>>;

  /**
   * Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_items: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialItemsItem>
  >;

  /**
   * Footer Secondary Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_secondary_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_secondary_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterSecondaryLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ClientsDocument
  | ClientsPostDocument
  | HomepageDocument
  | NewsPageDocument
  | NewsPostDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *AboutLower → Default → Primary*
 */
export interface AboutLowerSliceDefaultPrimary {
  /**
   * title field in *AboutLower → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Left Title
   * - **API ID Path**: about_lower.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * paragraghFirst field in *AboutLower → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Paragraph First
   * - **API ID Path**: about_lower.default.primary.paragraghfirst
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraghfirst: prismic.KeyTextField;

  /**
   * paragraghSecond field in *AboutLower → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Paragraph Second
   * - **API ID Path**: about_lower.default.primary.paragraghsecond
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraghsecond: prismic.KeyTextField;
}

/**
 * Default variation for AboutLower Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutLowerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutLowerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutLower*
 */
type AboutLowerSliceVariation = AboutLowerSliceDefault;

/**
 * AboutLower Shared Slice
 *
 * - **API ID**: `about_lower`
 * - **Description**: AboutLower
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutLowerSlice = prismic.SharedSlice<
  "about_lower",
  AboutLowerSliceVariation
>;

/**
 * Item in *AnimatedGrid → Default → Primary → Type URL Map*
 */
export interface AnimatedGridSliceDefaultPrimaryTypeUrlMapItem {
  /**
   * Key field in *AnimatedGrid → Default → Primary → Type URL Map*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the key
   * - **API ID Path**: animated_grid.default.primary.type_url_map[].key
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  key: prismic.SelectField<"partner" | "portfolio" | "production">;

  /**
   * Value field in *AnimatedGrid → Default → Primary → Type URL Map*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the corresponding URL
   * - **API ID Path**: animated_grid.default.primary.type_url_map[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;
}

/**
 * Item in *AnimatedGrid → Default → Primary → Projects*
 */
export interface AnimatedGridSliceDefaultPrimaryProjectsItem {
  /**
   * Name field in *AnimatedGrid → Default → Primary → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the project name
   * - **API ID Path**: animated_grid.default.primary.projects[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *AnimatedGrid → Default → Primary → Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_grid.default.primary.projects[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slug field in *AnimatedGrid → Default → Primary → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the project slug
   * - **API ID Path**: animated_grid.default.primary.projects[].slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Role field in *AnimatedGrid → Default → Primary → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the project role
   * - **API ID Path**: animated_grid.default.primary.projects[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Year field in *AnimatedGrid → Default → Primary → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the project year
   * - **API ID Path**: animated_grid.default.primary.projects[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * Type field in *AnimatedGrid → Default → Primary → Projects*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the project type
   * - **API ID Path**: animated_grid.default.primary.projects[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"partner" | "portfolio" | "production">;
}

/**
 * Primary content in *AnimatedGrid → Default → Primary*
 */
export interface AnimatedGridSliceDefaultPrimary {
  /**
   * Title field in *AnimatedGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the grid title
   * - **API ID Path**: animated_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Type URL Map field in *AnimatedGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_grid.default.primary.type_url_map[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  type_url_map: prismic.GroupField<
    Simplify<AnimatedGridSliceDefaultPrimaryTypeUrlMapItem>
  >;

  /**
   * Projects field in *AnimatedGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: animated_grid.default.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<
    Simplify<AnimatedGridSliceDefaultPrimaryProjectsItem>
  >;
}

/**
 * Default variation for AnimatedGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: AnimatedGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnimatedGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnimatedGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AnimatedGrid*
 */
type AnimatedGridSliceVariation = AnimatedGridSliceDefault;

/**
 * AnimatedGrid Shared Slice
 *
 * - **API ID**: `animated_grid`
 * - **Description**: AnimatedGrid component
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnimatedGridSlice = prismic.SharedSlice<
  "animated_grid",
  AnimatedGridSliceVariation
>;

/**
 * Item in *Brief → Default → Primary → Services*
 */
export interface BriefSliceDefaultPrimaryDataItem {
  /**
   * buttonName field in *Brief → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Button Name
   * - **API ID Path**: brief.default.primary.data[].buttonname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonname: prismic.KeyTextField;
}

/**
 * Primary content in *Brief → Default → Primary*
 */
export interface BriefSliceDefaultPrimary {
  /**
   * Title field in *Brief → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the title
   * - **API ID Path**: brief.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Desc field in *Brief → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the description
   * - **API ID Path**: brief.default.primary.desc
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  desc: prismic.KeyTextField;

  /**
   * Services field in *Brief → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: brief.default.primary.data[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  data: prismic.GroupField<Simplify<BriefSliceDefaultPrimaryDataItem>>;
}

/**
 * Default variation for Brief Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BriefSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BriefSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Brief*
 */
type BriefSliceVariation = BriefSliceDefault;

/**
 * Brief Shared Slice
 *
 * - **API ID**: `brief`
 * - **Description**: Brief section with title, description and services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BriefSlice = prismic.SharedSlice<"brief", BriefSliceVariation>;

/**
 * Item in *Carousel → Default → Primary → Carousel Items*
 */
export interface CarouselSliceDefaultPrimaryCarouselItemsItem {
  /**
   * card field in *Carousel → Default → Primary → Carousel Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Please Enter Card
   * - **API ID Path**: carousel.default.primary.carouselItems[].card
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card: prismic.LinkField;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Carousel Type field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the type of carousel
   * - **API ID Path**: carousel.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"actor" | "serie" | "news">;

  /**
   * Carousel Items field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselItems[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carouselItems: prismic.GroupField<
    Simplify<CarouselSliceDefaultPrimaryCarouselItemsItem>
  >;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel for displaying partner series or actors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * iframeLink field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter iFrame link
   * - **API ID Path**: contact.default.primary.iframelink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  iframelink: prismic.KeyTextField;

  /**
   * Address field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Adress
   * - **API ID Path**: contact.default.primary.address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Phone Number field in *Contact → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Please Enter Phone Number
   * - **API ID Path**: contact.default.primary.phone_number
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  phone_number: prismic.NumberField;

  /**
   * Title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Title
   * - **API ID Path**: contact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Description
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Display → Default → Primary → images*
 */
export interface DisplaySliceDefaultPrimaryImagesItem {
  /**
   * image field in *Display → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: display.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Display → Default → Primary → images*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Please Enter Link
   * - **API ID Path**: display.default.primary.images[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Display → Default → Primary*
 */
export interface DisplaySliceDefaultPrimary {
  /**
   * title field in *Display → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Title
   * - **API ID Path**: display.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * images field in *Display → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: display.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<DisplaySliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Display Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DisplaySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DisplaySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Display*
 */
type DisplaySliceVariation = DisplaySliceDefault;

/**
 * Display Shared Slice
 *
 * - **API ID**: `display`
 * - **Description**: Display
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DisplaySlice = prismic.SharedSlice<
  "display",
  DisplaySliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * phrase1 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: First Video's Text
   * - **API ID Path**: hero_section.default.primary.phrase1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phrase1: prismic.KeyTextField;

  /**
   * phrase2 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Second Video's Text
   * - **API ID Path**: hero_section.default.primary.phrase2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phrase2: prismic.KeyTextField;

  /**
   * HeroVideoPoster field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.herovideoposter
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herovideoposter: prismic.ImageField<never>;

  /**
   * videoSrc field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Video Source Link
   * - **API ID Path**: hero_section.default.primary.videosrc
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  videosrc: prismic.KeyTextField;

  /**
   * frameLink field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: iFrame's Link
   * - **API ID Path**: hero_section.default.primary.framelink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  framelink: prismic.KeyTextField;

  /**
   * gradient field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero_section.default.primary.gradient
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  gradient: prismic.BooleanField;

  /**
   * isVideo field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero_section.default.primary.isvideo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isvideo: prismic.BooleanField;

  /**
   * direction field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: "leftBottom" or "center"
   * - **API ID Path**: hero_section.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  direction: prismic.KeyTextField;

  /**
   * centerPhrase field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter The Center Phrase If It Exists ( Optional )
   * - **API ID Path**: hero_section.default.primary.centerphrase
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  centerphrase: prismic.KeyTextField;

  /**
   * imgLink field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.imglink
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imglink: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *Integration → Default → Primary → integrations*
 */
export interface IntegrationSliceDefaultPrimaryIntegrationsItem {
  /**
   * name field in *Integration → Default → Primary → integrations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Name
   * - **API ID Path**: integration.default.primary.integrations[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * image field in *Integration → Default → Primary → integrations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.default.primary.integrations[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *Integration → Default → Primary → integrations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Please Enter Link
   * - **API ID Path**: integration.default.primary.integrations[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Integration → Default → Primary*
 */
export interface IntegrationSliceDefaultPrimary {
  /**
   * title field in *Integration → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Title
   * - **API ID Path**: integration.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Integration → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Subtitle
   * - **API ID Path**: integration.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * integrations field in *Integration → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: integration.default.primary.integrations[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  integrations: prismic.GroupField<
    Simplify<IntegrationSliceDefaultPrimaryIntegrationsItem>
  >;
}

/**
 * Default variation for Integration Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntegrationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntegrationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Integration*
 */
type IntegrationSliceVariation = IntegrationSliceDefault;

/**
 * Integration Shared Slice
 *
 * - **API ID**: `integration`
 * - **Description**: Integration
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntegrationSlice = prismic.SharedSlice<
  "integration",
  IntegrationSliceVariation
>;

/**
 * Primary content in *Landing → Default → Primary*
 */
export interface LandingSliceDefaultPrimary {
  /**
   * firstLine field in *Landing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter first line
   * - **API ID Path**: landing.default.primary.firstline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  firstline: prismic.KeyTextField;

  /**
   * secondLine field in *Landing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Second Line
   * - **API ID Path**: landing.default.primary.secondline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondline: prismic.KeyTextField;

  /**
   * thirdLine field in *Landing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Third Line
   * - **API ID Path**: landing.default.primary.thirdline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  thirdline: prismic.KeyTextField;

  /**
   * span field in *Landing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter The Colored Span
   * - **API ID Path**: landing.default.primary.span
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  span: prismic.KeyTextField;
}

/**
 * Default variation for Landing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Landing*
 */
type LandingSliceVariation = LandingSliceDefault;

/**
 * Landing Shared Slice
 *
 * - **API ID**: `landing`
 * - **Description**: Landing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LandingSlice = prismic.SharedSlice<
  "landing",
  LandingSliceVariation
>;

/**
 * Item in *LogosMarquee → Default → Primary → data*
 */
export interface LogosMarqueeSliceDefaultPrimaryDataItem {
  /**
   * image field in *LogosMarquee → Default → Primary → data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logos_marquee.default.primary.data[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *LogosMarquee → Default → Primary → data*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter Logo's Link
   * - **API ID Path**: logos_marquee.default.primary.data[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *LogosMarquee → Default → Primary*
 */
export interface LogosMarqueeSliceDefaultPrimary {
  /**
   * direction field in *LogosMarquee → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the direction of the marquee
   * - **API ID Path**: logos_marquee.default.primary.direction
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  direction: prismic.KeyTextField;

  /**
   * data field in *LogosMarquee → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logos_marquee.default.primary.data[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  data: prismic.GroupField<Simplify<LogosMarqueeSliceDefaultPrimaryDataItem>>;
}

/**
 * Default variation for LogosMarquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosMarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogosMarqueeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LogosMarquee*
 */
type LogosMarqueeSliceVariation = LogosMarqueeSliceDefault;

/**
 * LogosMarquee Shared Slice
 *
 * - **API ID**: `logos_marquee`
 * - **Description**: LogosMarquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosMarqueeSlice = prismic.SharedSlice<
  "logos_marquee",
  LogosMarqueeSliceVariation
>;

/**
 * Item in *MiniServices → Default → Primary → data*
 */
export interface MiniServicesSliceDefaultPrimaryDataItem {
  /**
   * buttonName field in *MiniServices → Default → Primary → data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Button Name
   * - **API ID Path**: mini_services.default.primary.data[].buttonname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonname: prismic.KeyTextField;
}

/**
 * Primary content in *MiniServices → Default → Primary*
 */
export interface MiniServicesSliceDefaultPrimary {
  /**
   * data field in *MiniServices → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mini_services.default.primary.data[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  data: prismic.GroupField<Simplify<MiniServicesSliceDefaultPrimaryDataItem>>;
}

/**
 * Default variation for MiniServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MiniServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MiniServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MiniServices*
 */
type MiniServicesSliceVariation = MiniServicesSliceDefault;

/**
 * MiniServices Shared Slice
 *
 * - **API ID**: `mini_services`
 * - **Description**: Mini services section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MiniServicesSlice = prismic.SharedSlice<
  "mini_services",
  MiniServicesSliceVariation
>;

/**
 * Item in *NewsSlider → Default → Primary → Cards*
 */
export interface NewsSliderSliceDefaultPrimaryCardsItem {
  /**
   * Reference Link field in *NewsSlider → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add Card Link (Required)
   * - **API ID Path**: news_slider.default.primary.cards[].referencelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  referencelink: prismic.LinkField;
}

/**
 * Primary content in *NewsSlider → Default → Primary*
 */
export interface NewsSliderSliceDefaultPrimary {
  /**
   * Section Title field in *NewsSlider → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select section title
   * - **API ID Path**: news_slider.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  title: prismic.SelectField<"Latest News" | "Related Articles">;

  /**
   * Section Text field in *NewsSlider → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Provide a brief description or introduction for this section
   * - **API ID Path**: news_slider.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Cards field in *NewsSlider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_slider.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<NewsSliderSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for NewsSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default News Slider variation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsSlider*
 */
type NewsSliderSliceVariation = NewsSliderSliceDefault;

/**
 * NewsSlider Shared Slice
 *
 * - **API ID**: `news_slider`
 * - **Description**: News Slider component
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSliderSlice = prismic.SharedSlice<
  "news_slider",
  NewsSliderSliceVariation
>;

/**
 * Item in *Services → Default → Primary → Services → Service Items*
 */
export interface ServicesSliceDefaultPrimaryServicesListServicesItemsItem {
  /**
   * Service Item field in *Services → Default → Primary → Services → Service Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter service item
   * - **API ID Path**: services.default.primary.services_list[].services_items[].service_item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_item: prismic.KeyTextField;
}

/**
 * Item in *Services → Default → Primary → Services*
 */
export interface ServicesSliceDefaultPrimaryServicesListItem {
  /**
   * Category Name field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter category name
   * - **API ID Path**: services.default.primary.services_list[].category_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_name: prismic.KeyTextField;

  /**
   * Service Items field in *Services → Default → Primary → Services*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services_list[].services_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services_items: prismic.NestedGroupField<
    Simplify<ServicesSliceDefaultPrimaryServicesListServicesItemsItem>
  >;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Title field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Title
   * - **API ID Path**: services.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Services field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services_list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services_list: prismic.GroupField<
    Simplify<ServicesSliceDefaultPrimaryServicesListItem>
  >;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Item in *Team → Default → Primary → team*
 */
export interface TeamSliceDefaultPrimaryTeamItem {
  /**
   * image field in *Team → Default → Primary → team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *Team → Default → Primary → team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Team Member's Name ( Must )
   * - **API ID Path**: team.default.primary.team[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * position field in *Team → Default → Primary → team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Team Member's Position ( Must )
   * - **API ID Path**: team.default.primary.team[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Title
   * - **API ID Path**: team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * team field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryTeamItem>>;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Primary content in *TopDivider → Default → Primary*
 */
export interface TopDividerSliceDefaultPrimary {
  /**
   * title field in *TopDivider → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Title ( Must )
   * - **API ID Path**: top_divider.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for TopDivider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopDividerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TopDividerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TopDivider*
 */
type TopDividerSliceVariation = TopDividerSliceDefault;

/**
 * TopDivider Shared Slice
 *
 * - **API ID**: `top_divider`
 * - **Description**: TopDivider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopDividerSlice = prismic.SharedSlice<
  "top_divider",
  TopDividerSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * video field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Video URL
   * - **API ID Path**: video.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video: prismic.KeyTextField;

  /**
   * videoOpen field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Video Open URL
   * - **API ID Path**: video.default.primary.videoopen
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  videoopen: prismic.KeyTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

/**
 * Item in *WorkWithUs → Default → Primary → partnership_options*
 */
export interface WorkWithUsSliceDefaultPrimaryPartnershipOptionsItem {
  /**
   * option_title field in *WorkWithUs → Default → Primary → partnership_options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Option Title
   * - **API ID Path**: work_with_us.default.primary.partnership_options[].option_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  option_title: prismic.KeyTextField;

  /**
   * option_description field in *WorkWithUs → Default → Primary → partnership_options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Option Description
   * - **API ID Path**: work_with_us.default.primary.partnership_options[].option_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  option_description: prismic.KeyTextField;

  /**
   * button_text field in *WorkWithUs → Default → Primary → partnership_options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Button Text
   * - **API ID Path**: work_with_us.default.primary.partnership_options[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * calendarLink field in *WorkWithUs → Default → Primary → partnership_options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Calendar Link
   * - **API ID Path**: work_with_us.default.primary.partnership_options[].calendarlink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calendarlink: prismic.KeyTextField;
}

/**
 * Primary content in *WorkWithUs → Default → Primary*
 */
export interface WorkWithUsSliceDefaultPrimary {
  /**
   * title field in *WorkWithUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Title
   * - **API ID Path**: work_with_us.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *WorkWithUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Description
   * - **API ID Path**: work_with_us.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * partnership_options field in *WorkWithUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_with_us.default.primary.partnership_options[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  partnership_options: prismic.GroupField<
    Simplify<WorkWithUsSliceDefaultPrimaryPartnershipOptionsItem>
  >;
}

/**
 * Default variation for WorkWithUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkWithUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkWithUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkWithUs*
 */
type WorkWithUsSliceVariation = WorkWithUsSliceDefault;

/**
 * WorkWithUs Shared Slice
 *
 * - **API ID**: `work_with_us`
 * - **Description**: WorkWithUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkWithUsSlice = prismic.SharedSlice<
  "work_with_us",
  WorkWithUsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ClientsDocument,
      ClientsDocumentData,
      ClientsDocumentDataSlicesSlice,
      ClientsPostDocument,
      ClientsPostDocumentData,
      ClientsPostDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NewsPageDocument,
      NewsPageDocumentData,
      NewsPageDocumentDataSlicesSlice,
      NewsPostDocument,
      NewsPostDocumentData,
      NewsPostDocumentDataTagsItem,
      NewsPostDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavItemsItem,
      SettingsDocumentDataSocialItemsItem,
      SettingsDocumentDataFooterSecondaryLinksItem,
      AllDocumentTypes,
      AboutLowerSlice,
      AboutLowerSliceDefaultPrimary,
      AboutLowerSliceVariation,
      AboutLowerSliceDefault,
      AnimatedGridSlice,
      AnimatedGridSliceDefaultPrimaryTypeUrlMapItem,
      AnimatedGridSliceDefaultPrimaryProjectsItem,
      AnimatedGridSliceDefaultPrimary,
      AnimatedGridSliceVariation,
      AnimatedGridSliceDefault,
      BriefSlice,
      BriefSliceDefaultPrimaryDataItem,
      BriefSliceDefaultPrimary,
      BriefSliceVariation,
      BriefSliceDefault,
      CarouselSlice,
      CarouselSliceDefaultPrimaryCarouselItemsItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      DisplaySlice,
      DisplaySliceDefaultPrimaryImagesItem,
      DisplaySliceDefaultPrimary,
      DisplaySliceVariation,
      DisplaySliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      IntegrationSlice,
      IntegrationSliceDefaultPrimaryIntegrationsItem,
      IntegrationSliceDefaultPrimary,
      IntegrationSliceVariation,
      IntegrationSliceDefault,
      LandingSlice,
      LandingSliceDefaultPrimary,
      LandingSliceVariation,
      LandingSliceDefault,
      LogosMarqueeSlice,
      LogosMarqueeSliceDefaultPrimaryDataItem,
      LogosMarqueeSliceDefaultPrimary,
      LogosMarqueeSliceVariation,
      LogosMarqueeSliceDefault,
      MiniServicesSlice,
      MiniServicesSliceDefaultPrimaryDataItem,
      MiniServicesSliceDefaultPrimary,
      MiniServicesSliceVariation,
      MiniServicesSliceDefault,
      NewsSliderSlice,
      NewsSliderSliceDefaultPrimaryCardsItem,
      NewsSliderSliceDefaultPrimary,
      NewsSliderSliceVariation,
      NewsSliderSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryServicesListServicesItemsItem,
      ServicesSliceDefaultPrimaryServicesListItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryTeamItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TopDividerSlice,
      TopDividerSliceDefaultPrimary,
      TopDividerSliceVariation,
      TopDividerSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
      WorkWithUsSlice,
      WorkWithUsSliceDefaultPrimaryPartnershipOptionsItem,
      WorkWithUsSliceDefaultPrimary,
      WorkWithUsSliceVariation,
      WorkWithUsSliceDefault,
    };
  }
}
