// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_lower: dynamic(() => import("./AboutLower")),
  animated_grid: dynamic(() => import("./AnimatedGrid")),
  brief: dynamic(() => import("./Brief")),
  carousel: dynamic(() => import("./Carousel")),
  contact: dynamic(() => import("./Contact")),
  display: dynamic(() => import("./Display")),
  hero_section: dynamic(() => import("./HeroSection")),
  integration: dynamic(() => import("./Integration")),
  landing: dynamic(() => import("./Landing")),
  logos_marquee: dynamic(() => import("./LogosMarquee")),
  mini_services: dynamic(() => import("./MiniServices")),
  news_slider: dynamic(() => import("./NewsSlider")),
  services: dynamic(() => import("./Services")),
  team: dynamic(() => import("./Team")),
  top_divider: dynamic(() => import("./TopDivider")),
  video: dynamic(() => import("./Video")),
  work_with_us: dynamic(() => import("./WorkWithUs")),
};
